[package]
name = "squalr-engine-processes"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2021"
# build = "build.rs"

[dependencies]
squalr-engine-common = { path = "../squalr-engine-common" }
once_cell = ">=1.20.2"
rayon = ">=1.10.0"
sysinfo = ">=0.31.2"
windows-sys = { version = ">=0.59", features = [
    "Win32_Graphics_Gdi",
    "Win32_Foundation",
    "Win32_System_ProcessStatus",
    "Win32_System_SystemInformation",
    "Win32_System_Threading",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging",
]}

[build-dependencies]

