[package]
name = "squalr-engine-processes"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2021"
# build = "build.rs"

[dependencies]
squalr-engine-common = { path = "../squalr-engine-common" }
sysinfo = ">=0.31.2"
windows-sys = { version = ">=0.52", features = ["Win32_UI_Shell", "Win32_UI_WindowsAndMessaging", "Win32_System_SystemInformation", "Win32_Foundation", "Win32_System_Threading", "Win32_Graphics_Gdi"] }

[build-dependencies]

