[package]
name = "squalr-engine-processes"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2021"
# build = "build.rs"

[dependencies]
squalr-engine-common = { path = "../squalr-engine-common" }
sysinfo = ">=0.30"
winapi = { version = ">=0.3", features = ["winuser", "shellapi"] }

[build-dependencies]

