[package]
name = "squalr-engine-memory"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2021"
# build = "build.rs"

[dependencies]
squalr-engine-common = { path = "../squalr-engine-common" }
squalr-engine-processes = { path = "../squalr-engine-processes" }
bitflags = ">=1.3.2"
sysinfo = ">=0.30"
winapi = { version = ">=0.3.9", features = ["winnt", "psapi", "processthreadsapi", "memoryapi"] }

[build-dependencies]

