[package]
name = "squalr"
version = "0.1.1"
authors = ["Zachary Canann"]
edition = "2024"
# build = "build.rs"

[dependencies]
squalr-engine = { path = "../squalr-engine" }
squalr-engine-api = { path = "../squalr-engine-api" }
eframe = ">=0.32.3"
log = ">=0.4.27"
wasm-bindgen = "0.2"

[build-dependencies]
winresource = ">=0.1.20"
