[package]
name = "squalr-engine-common"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2021"
# build = "build.rs"

[dependencies]
futures = ">=0.3"
tokio = { version = ">=1.38", features = ["full"] }
tokio-util = ">=0.7.11"
uuid = { version = ">=1.9.1", features = ["v4"] }

[build-dependencies]

