[package]
name = "squalr-engine-common"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2024"
# build = "build.rs"

[dependencies]
futures = ">=0.3"
hex = { version = ">=0.4.3" }
rayon = { version = ">=1.10.0" }
serde = { version = ">=1.0.0", features = ["derive"] }
serde_json = ">=1.0.0"
uuid = { version = ">=1.9.1", features = ["v4"] }

[build-dependencies]

