[package]
name = "squalr-engine-common"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2021"
# build = "build.rs"

[dependencies]
lazy_static = ">=1.5"
uuid = { version = ">=1.9.1", features = ["v4"] }

[build-dependencies]

