[package]
name = "squalr-engine-common"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2021"
# build = "build.rs"

[dependencies]
futures = ">=0.3"
uuid = { version = ">=1.9.1", features = ["v4"] }
rayon = { version = ">=1.10.0" }

[build-dependencies]

