[package]
name = "squalr-android"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2024"
# build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
slint-mvvm = { path = "../slint-mvvm" }
slint-mvvm-macros = { path = "../slint-mvvm-macros" }
squalr-engine = { path = "../squalr-engine" }
squalr-engine-architecture = { path = "../squalr-engine-architecture" }
squalr-engine-common = { path = "../squalr-engine-common" }
squalr-engine-debuggers = { path = "../squalr-engine-debuggers" }
squalr-engine-memory = { path = "../squalr-engine-memory" }
squalr-engine-processes = { path = "../squalr-engine-processes" }
squalr-engine-projects = { path = "../squalr-engine-projects" }
squalr-engine-scanning = { path = "../squalr-engine-scanning" }
squalr-engine-scripting = { path = "../squalr-engine-scripting" }
futures = ">=0.3"
log = ">=0.4.22"
rayon = ">=1.10.0"
serde = { version = ">=1.0.0", features = ["derive"] }
serde_json = ">=1.0.0"
slint = { version = ">=1.9.1", default-features = false, features = ["accessibility", "backend-android-activity-06", "compat-1-2", "std"] }
structopt = ">=0.3"
sysinfo = ">=0.30"

[build-dependencies]
slint-build = { version = ">=1.7.2" }
winresource = ">=0.1.17"
