[package]
name = "squalr-engine-scanning"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2021"
# build = "build.rs"

[dependencies]
squalr-engine-architecture = { path = "../squalr-engine-architecture" }
squalr-engine-common = { path = "../squalr-engine-common" }
squalr-engine-memory = { path = "../squalr-engine-memory" }
squalr-engine-processes = { path = "../squalr-engine-processes" }
bitflags = ">=2.6.0"
bytemuck = ">=1.17.0"
dashmap = { version = ">=6.0.1", features = ["inline", "rayon"] }
futures = ">=0.3.30"
lazy_static = ">=1.5.0"
rangemap = { version = ">=1.5.1" }
rayon = "1.10.0"
seq-macro = ">=0.3.5"
serde = { version = ">=1.0.0", features = ["derive"] }
serde_json = ">=1.0.0"
sysinfo = ">=0.31.2"
uuid = { version = ">=1.10.0", features = ["v4"] }

[build-dependencies]

