[package]
name = "squalr-engine-scanning"
version = "0.1.0"
authors = ["Zachary Canann"]
edition = "2021"
# build = "build.rs"

[dependencies]
squalr-engine-architecture = { path = "../squalr-engine-architecture" }
squalr-engine-common = { path = "../squalr-engine-common" }
squalr-engine-memory = { path = "../squalr-engine-memory" }
squalr-engine-processes = { path = "../squalr-engine-processes" }
bitflags = ">=1.3.2"
futures = ">=0.3"
sysinfo = ">=0.30"
tokio = { version = ">=1.38", features = ["full"] }
tokio-util = ">=0.7.11"
uuid = { version = ">=1.9.1", features = ["v4"] }

[build-dependencies]

